<?php

namespace App\Form;

use Symfony\Bridge\Doctrine\Form\DataTransformer\CollectionToArrayTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\TagsTransformer;
use Doctrine\ORM\EntityManagerInterface;

class TagsType extends AbstractType
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->addModelTransformer(new CollectionToArrayTransformer(), true)
            ->addModelTransformer(new TagsTransformer( $this->entityManager), true)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('attr',[
            'class'=> 'tag-input',
            'style'=> 'border-bottom: 0px;'
        ]);
        $resolver->setDefault('required', false);
    }

    public function getParent()
    {
        return TextType::class; // TODO: Change the autogenerated stub
    }


}
