<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerApKIbKM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerApKIbKM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerApKIbKM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerApKIbKM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerApKIbKM\App_KernelDevDebugContainer([
    'container.build_hash' => 'ApKIbKM',
    'container.build_id' => 'af148680',
    'container.build_time' => 1635250696,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerApKIbKM');
